<a href="https://colab.research.google.com/github/dipaksavitre-don/assiment-24/blob/main/assignmnet24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

classification_dataset = pd.read_csv(r"/content/Heart_Disease_Classification.csv")
regresssion_dataset = pd.read_csv(r"/content/House_Price_Regression.csv")

In [45]:
classification_dataset.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,67,1,3,118,327,0,2,86,0,3.7,0,2,2,1
1,57,1,3,102,227,0,2,195,0,0.6,1,2,0,1
2,43,0,2,135,266,1,2,153,1,3.9,1,2,2,1
3,71,1,1,124,269,0,1,78,1,4.2,1,1,1,1
4,36,1,0,95,286,1,0,132,0,2.2,2,3,2,1

In [46]:
regresssion_dataset.head()

,Area_sqft,Bedrooms,Bathrooms,Stories,Parking,House_Age,Location_Score,Price
0,1662,1,1,3,2,16,1,1488864
1,856,3,1,1,0,10,7,1227430
2,2124,2,1,1,0,3,2,2067157
3,2821,4,1,3,2,25,1,2483821
4,3590,4,2,2,2,12,3,3489480

In [9]:
# cleaning the classsification dataset
classification_dataset.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [10]:
classification_dataset = classification_dataset.drop_duplicates()

In [11]:
classification_dataset.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [47]:

classification_dataset.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,52.860000,0.546667,1.450000,133.236667,250.720000,0.476667,0.963333,135.390000,0.543333,2.232667,1.006667,1.463333,1.473333,0.893333
std,14.367387,0.498649,1.182721,27.034612,57.092733,0.500290,0.831239,38.697583,0.498951,1.299987,0.809613,1.163257,1.116592,0.309205
min,29.000000,0.000000,0.000000,90.000000,150.000000,0.000000,0.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,40.000000,0.000000,0.000000,110.000000,202.000000,0.000000,0.000000,103.000000,0.000000,1.100000,0.000000,0.000000,0.000000,1.000000
50%,53.000000,1.000000,1.000000,135.000000,253.000000,0.000000,1.000000,137.000000,1.000000,2.300000,1.000000,1.000000,2.000000,1.000000
75%,65.000000,1.000000,3.000000,156.000000,302.250000,1.000000,2.000000,169.500000,1.000000,3.400000,2.000000,3.000000,2.000000,1.000000
max,77.000000,1.000000,3.000000,180.000000,350.000000,1.000000,2.000000,200.000000,1.000000,4.500000,2.000000,3.000000,3.000000,1.000000

In [48]:
# filling the null values in each columns
for i in classification_dataset.columns:
    if classification_dataset[i].isnull().sum()>0:
        if classification_dataset[i].dtype !='object':
            mean  = classification_dataset.loc[classification_dataset[i].notna(),i].mean()
            classification_dataset[i] = classification_dataset[i].fillna(mean)
        else:
            most_repeted = classification_dataset[i].value_counts().idxmax()
            classification_dataset[i] = classification_dataset[i].fillna(most_repeted)

In [49]:
# cheaking the dataset after cleanin
classification_dataset.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,52.860000,0.546667,1.450000,133.236667,250.720000,0.476667,0.963333,135.390000,0.543333,2.232667,1.006667,1.463333,1.473333,0.893333
std,14.367387,0.498649,1.182721,27.034612,57.092733,0.500290,0.831239,38.697583,0.498951,1.299987,0.809613,1.163257,1.116592,0.309205
min,29.000000,0.000000,0.000000,90.000000,150.000000,0.000000,0.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,40.000000,0.000000,0.000000,110.000000,202.000000,0.000000,0.000000,103.000000,0.000000,1.100000,0.000000,0.000000,0.000000,1.000000
50%,53.000000,1.000000,1.000000,135.000000,253.000000,0.000000,1.000000,137.000000,1.000000,2.300000,1.000000,1.000000,2.000000,1.000000
75%,65.000000,1.000000,3.000000,156.000000,302.250000,1.000000,2.000000,169.500000,1.000000,3.400000,2.000000,3.000000,2.000000,1.000000
max,77.000000,1.000000,3.000000,180.000000,350.000000,1.000000,2.000000,200.000000,1.000000,4.500000,2.000000,3.000000,3.000000,1.000000

In [15]:
classification_dataset.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [50]:
# cleaning the regration dataset
regresssion_dataset.describe()

,Area_sqft,Bedrooms,Bathrooms,Stories,Parking,House_Age,Location_Score,Price
count,300.000000,300.000000,300.00000,300.000000,300.000000,300.000000,300.000000,3.000000e+02
mean,2274.140000,2.873333,2.41000,2.096667,1.470000,15.706667,5.646667,2.348966e+06
std,1043.902343,1.379723,1.11926,0.797565,1.131386,8.675531,2.874491,8.712496e+05
min,507.000000,1.000000,1.00000,1.000000,0.000000,0.000000,1.000000,4.719150e+05
25%,1361.500000,2.000000,1.00000,1.000000,0.000000,8.750000,3.000000,1.585811e+06
50%,2366.500000,3.000000,2.00000,2.000000,2.000000,16.000000,6.000000,2.446820e+06
75%,3163.750000,4.000000,3.00000,3.000000,2.000000,23.000000,8.000000,3.039549e+06
max,3998.000000,5.000000,4.00000,3.000000,3.000000,30.000000,10.000000,4.260526e+06

In [51]:
# Cleanin the incorrect values
columns_to_fix = ['age', 'sex', 'cp', 'chol', 'fbs']

for col in columns_to_fix:
    mean_val = classification_dataset.loc[classification_dataset[col] > 0, col].mean()
    # Replace negative values with the mean
    classification_dataset.loc[classification_dataset[col] <= 0, col] = int(mean_val)

In [52]:
regresssion_dataset = regresssion_dataset.drop_duplicates()

In [53]:
regresssion_dataset.dtypes

Area_sqft         int64
Bedrooms          int64
Bathrooms         int64
Stories           int64
Parking           int64
House_Age         int64
Location_Score    int64
Price             int64
dtype: object

In [54]:
regresssion_dataset.describe()

,Area_sqft,Bedrooms,Bathrooms,Stories,Parking,House_Age,Location_Score,Price
count,300.000000,300.000000,300.00000,300.000000,300.000000,300.000000,300.000000,3.000000e+02
mean,2274.140000,2.873333,2.41000,2.096667,1.470000,15.706667,5.646667,2.348966e+06
std,1043.902343,1.379723,1.11926,0.797565,1.131386,8.675531,2.874491,8.712496e+05
min,507.000000,1.000000,1.00000,1.000000,0.000000,0.000000,1.000000,4.719150e+05
25%,1361.500000,2.000000,1.00000,1.000000,0.000000,8.750000,3.000000,1.585811e+06
50%,2366.500000,3.000000,2.00000,2.000000,2.000000,16.000000,6.000000,2.446820e+06
75%,3163.750000,4.000000,3.00000,3.000000,2.000000,23.000000,8.000000,3.039549e+06
max,3998.000000,5.000000,4.00000,3.000000,3.000000,30.000000,10.000000,4.260526e+06

In [55]:
regresssion_dataset.isnull().sum()

Area_sqft         0
Bedrooms          0
Bathrooms         0
Stories           0
Parking           0
House_Age         0
Location_Score    0
Price             0
dtype: int64

In [22]:
# filling the null values in each columns
for i in regresssion_dataset.columns:
    if regresssion_dataset[i].isnull().sum()>0:
        if regresssion_dataset[i].dtype =='number':
            mean  = regresssion_dataset.loc[regresssion_dataset[i].notna(),i].mean()
            regresssion_dataset[i] = regresssion_dataset[i].fillna(mean)
        else:
            most_repeted = regresssion_dataset[i].value_counts().idxmax()
            regresssion_dataset[i] = regresssion_dataset[i].fillna(most_repeted)

In [56]:
classification_dataset.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [57]:
# spling the indipendent and targated features of each dataset
x_classification = classification_dataset[['age', 'sex', 'cp', 'chol',
       'fbs','restecg']]
y_classfication = classification_dataset['target']

In [58]:
x_classification.select_dtypes(include='number').columns

Index(['age', 'sex', 'cp', 'chol', 'fbs', 'restecg'], dtype='object')

In [59]:
regresssion_dataset.columns

Index(['Area_sqft', 'Bedrooms', 'Bathrooms', 'Stories', 'Parking', 'House_Age',
       'Location_Score', 'Price'],
      dtype='object')

In [60]:
x_regrassion = regresssion_dataset[['Area_sqft', 'Bedrooms', 'Bathrooms', 'Stories', 'Parking', 'House_Age', 'Location_Score']]
y_regrassion = regresssion_dataset['Price']

In [61]:
# converting all numerical columns into integer
xc_numcols = x_classification.select_dtypes(include='number').columns
x_classification[xc_numcols] = x_classification[xc_numcols].astype(int)

xr_numcols = x_regrassion.select_dtypes(include='number').columns
x_regrassion[xr_numcols] = x_regrassion[xr_numcols].astype(int)

/tmp/ipykernel_468/3417485739.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_classification[xc_numcols] = x_classification[xc_numcols].astype(int)
/tmp/ipykernel_468/3417485739.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_regrassion[xr_numcols] = x_regrassion[xr_numcols].astype(int)

In [62]:
# performing one hot encoding on categorical columns
xc_catcols = x_classification.select_dtypes(include='object').columns
x_classification = pd.get_dummies(x_classification,columns=xc_catcols)

In [63]:
xr_catcols = x_regrassion.select_dtypes(include='object').columns
x_regrassion = pd.get_dummies(x_regrassion,columns=xr_catcols)

In [64]:
# standard scaling the numerical columns
from sklearn.preprocessing import StandardScaler
xc_scaler = StandardScaler()
x_classification[xc_numcols] = xc_scaler.fit_transform(x_classification[xc_numcols])
xr_scaler = StandardScaler()
x_regrassion[xr_numcols] = xr_scaler.fit_transform(x_regrassion[xr_numcols])

In [33]:
# spliting dataset int traning and testing dataframes
from sklearn.model_selection import train_test_split

xc_train,xc_test,yc_train,yc_test = train_test_split(x_classification,y_classfication,random_state=42,shuffle=True,test_size=0.33)

In [34]:
xr_train,xr_test,yr_train,yr_test = train_test_split(x_regrassion,y_regrassion,random_state=42,shuffle=True,test_size=0.33)

In [67]:
"""Q2. (Classification Algorithms)
On the classification dataset, train and evaluate the following models:
Logistic Regression
Decision Tree Classifier
Support Vector Machine (SVM)
K-Nearest Neighbors (KNN)
Naive Bayes
For each model:
Train the model
Make predictions
Calculate Accuracy, Confusion Matrix, and Classification Report
Create a comparison table of all models’ performance."""

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression()
logistic_model.fit(xc_train,yc_train)

LogisticRegression()

In [35]:
from sklearn.tree import DecisionTreeClassifier

decision_model = DecisionTreeClassifier()
decision_model.fit(xc_train,yc_train)

DecisionTreeClassifier()

In [36]:
from sklearn.neighbors import KNeighborsClassifier

K_model = KNeighborsClassifier(11)
K_model.fit(xc_train,yc_train)

KNeighborsClassifier(n_neighbors=11)

In [37]:
from sklearn.naive_bayes import GaussianNB
Navi_model = GaussianNB()
Navi_model.fit(xc_train,yc_train)

GaussianNB()

In [68]:
models = {
    'logistic_model':logistic_model,
    'decision-tree_model':decision_model,
    'KNN_model':K_model,
    'Navi-bias_model':Navi_model

}

In [69]:
# confusion matrix for each model
from sklearn.metrics import confusion_matrix
for i in models:
    x = models[i]
    y_pred = x.predict(xc_test)
    print(f"Confusion matrix of:{i}\n{confusion_matrix(yc_test,y_pred)}")

Confusion matrix of:logistic_model
[[ 0 10]
 [ 0 89]]
Confusion matrix of:decision-tree_model
[[ 0 10]
 [ 4 85]]
Confusion matrix of:KNN_model
[[ 0 10]
 [ 0 89]]
Confusion matrix of:Navi-bias_model
[[ 0 10]
 [ 0 89]]

In [70]:
# Accuracy of each model
from sklearn.metrics import accuracy_score
for i in models:
    x = models[i]
    y_pred = x.predict(xc_test)
    print(f"Accuracy for:{i}\n{accuracy_score(yc_test,y_pred)}")

Accuracy for:logistic_model
0.898989898989899
Accuracy for:decision-tree_model
0.8585858585858586
Accuracy for:KNN_model
0.898989898989899
Accuracy for:Navi-bias_model
0.898989898989899

In [71]:
# classification report for each Model
from sklearn.metrics import classification_report
for i in models:
    x = models[i]
    y_pred = x.predict(xc_test)
    print(f"Classification Report for:{i}\n{classification_report(yc_test,y_pred)}")

Classification Report for:logistic_model
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.90      1.00      0.95        89

    accuracy                           0.90        99
   macro avg       0.45      0.50      0.47        99
weighted avg       0.81      0.90      0.85        99

Classification Report for:decision-tree_model
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.89      0.96      0.92        89

    accuracy                           0.86        99
   macro avg       0.45      0.48      0.46        99
weighted avg       0.80      0.86      0.83        99

Classification Report for:KNN_model
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.90      1.00      0.95        89

    accuracy                           0.90        99
   macro avg       0.45      0.50      0.47        99
weighted avg       0.81      0.90      0.85        99

Classification Report for:Navi-bias_model
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.90      1.00      0.95        89

    accuracy                           0.90        99
   macro avg       0.45      0.50      0.47        99
weighted avg       0.81      0.90      0.85        99

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [72]:
reports = {}

for name, model in models.items():
    y_pred = model.predict(xc_test)
    report = classification_report(yc_test, y_pred, output_dict=True)
    reports[name] = report['weighted avg']  # use weighted avg for overall comparison

# Convert to DataFrame
comparison_table = pd.DataFrame(reports).T
print(comparison_table)

                     precision    recall  f1-score  support
logistic_model        0.808183  0.898990  0.851171     99.0
decision-tree_model   0.804359  0.858586  0.830588     99.0
KNN_model             0.808183  0.898990  0.851171     99.0
Navi-bias_model       0.808183  0.898990  0.851171     99.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [73]:
"""Q3. (Regression Algorithms)
On the regression dataset, train and evaluate the following models:
Linear Regression
Decision Tree Regressor
Support Vector Regressor (SVR)
K-Nearest Neighbors Regressor
For each model:
Train the model
Make predictions
Calculate R2 Score
Create a comparison table showing which model performed best."""

'Q3. (Regression Algorithms)\nOn the regression dataset, train and evaluate the following models:\nLinear Regression\nDecision Tree Regressor\nSupport Vector Regressor (SVR)\nK-Nearest Neighbors Regressor\nFor each model:\nTrain the model\nMake predictions\nCalculate R2 Score\nCreate a comparison table showing which model performed best.'

In [74]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()
linear_model.fit(xr_train,yr_train)

LinearRegression()

In [76]:
from sklearn.tree import DecisionTreeRegressor

dr_model = DecisionTreeRegressor()
dr_model.fit(xr_train,yr_train)

DecisionTreeRegressor()

In [77]:
from sklearn.svm import SVR

svr = SVR()
svr.fit(xr_train,yr_train)

SVR()

In [78]:
from sklearn.neighbors import KNeighborsRegressor

knr_model = KNeighborsRegressor()

knr_model.fit(xr_train,yr_train)

KNeighborsRegressor()

In [79]:
models2 = {
    'Decision Tree':dr_model,
    'Support Vector Machine':svr,
    'K nerest nabors':knr_model
}

In [80]:
from sklearn.metrics import r2_score
performance = {}

for name,model in models2.items():
    y_pre  = model.predict(xr_test)
    score = r2_score(yr_test,y_pre)
    print(f"R2 Score for model:{name} is:\n{score}")
    performance[name] = score
performance = pd.DataFrame([performance])

R2 Score for model:Decision Tree is:
0.9040127403999164
R2 Score for model:Support Vector Machine is:
-0.002009046084786803
R2 Score for model:K nerest nabors is:
0.8030700754048028

In [81]:
# comparision table
performance

   Decision Tree  Support Vector Machine  K nerest nabors
0       0.904013               -0.002009          0.80307

In [84]:
regration_cols = xr_train.columns
classification_cols = xc_train.columns

In [85]:
"""Q4. (Best Model Selection & Saving)
From Q2 and Q3:
Select the best classification model and best regression model based on
performance metrics.
Save both best models using joblib (also save scaler and columns if used)."""

# best classification model is KNN
# best regration model is also and K nerest nabors

# savin the models

import joblib as jb
jb.dump(K_model,'Knn-classification.pki')
jb.dump(knr_model,'Knn-regration.pki')
jb.dump(xc_scaler,'classification-scaler.pki')
jb.dump(xr_scaler,'regration-scaler.pki')
jb.dump(regration_cols,'regration-columns.pki')
jb.dump(classification_cols,'classification-columns.pki')

['classification-columns.pki']